name: ArmorEffect
main: VirVolta\ArmorEffect\ArmorEffect
api: [ 5.0.0 ]
authors:
  - VirVolta
  - Yakuuuuuuuuuuuuuuu
  - Refaltor
version: 1.0.0
description: Plugin for putting effects on armor pieces
